### ISSUE TITLE
Does not respect netlify.toml?

### ISSUE THREAD

**Issue by screendriver** [nwtgck/actions-netlify#168]
Could it be that this GitHub action does not respect configurations in [netlify.tom](https://docs.netlify.com/configure-builds/file-based-configuration/)? For example I have defined following redirect rule

```toml
[[redirects]]
  from = "https://me.com/*"
  to = "https://www.me.io/:splat"
  status = 301
  force = true
```

This redirect worked as expected before I switched from using `netlify-cli` in my npm scripts manually to this GitHub action 🤔
