### ISSUE TITLE
Action seems to erroneously state credentials not provided 

### ISSUE THREAD

**Issue by eliperelman** [nwtgck/actions-netlify#198]
I am attempting to run this action that has been in place, but appears to now be failing that credentials are not provided. The secret appears to be passed according to the logs:

<img width="438" alt="Screen Shot 2020-06-23 at 2 33 35 PM" src="https://user-images.githubusercontent.com/285899/85450891-e6165d00-b55e-11ea-91fd-2770f487bd51.png">

This is my job for the relevant action:

```yml
deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [setup, compile]
    if: ${{ needs.setup.outputs.affected-deploys != '[]' }}
    strategy:
      matrix:
        node: ['12.x']
        deploy: ${{ fromJson(needs.setup.outputs.affected-deploys) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set cache directory
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Restore cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Set up Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        env:
          CACHE_HIT: ${{ steps.yarn-cache.outputs.cache-hit }}
        run: tools/scripts/yarn-ci.sh

      - name: Restore compilation
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist/

      - run: touch dist/apps/${{ matrix.deploy.project }}/.prod.env
      - run: touch dist/apps/${{ matrix.deploy.project }}/.env

      - uses: c-py/action-dotenv-to-setenv@v1
        with:
          env-file: dist/apps/${{ matrix.deploy.project }}/.prod.env
        env:
          DOTENV_DEFAULT: dist/apps/${{ matrix.deploy.project }}/.env

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: dist/apps/${{ matrix.deploy.project }}
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-commit-comment: false
          netlify-config-path: ./netlify.toml
          functions-dir: dist/functions/
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
```

Thanks for helping out!
