### ISSUE TITLE
environment variables not working if I have build turned off

### ISSUE THREAD

**Issue by jpangelle** [nwtgck/actions-netlify#227]
I turned the Builds off in Netlify so that this Github Action can do my builds and deploys for me. However, the environment variables I set in Netlify do not work unless I let Netlify build for me. Is there a way to pass my site environment variables in this action? Has anyone else run into this issue.

My `deploy-to-prod.yml` job:

```yml
name: Deploy to Netlify

on:
  push:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hallee/eslint-action@1.0.3
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
  deploy-to-production:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Deploy
        uses: nwtgck/actions-netlify@v1.1
        with:
          deploy-message: ${{ github.event.head_commit.message }}
          enable-commit-comment: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
          production-branch: master
          production-deploy: true
          publish-dir: 'build'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
```

**Comment by jpangelle** [comment]
SOLVED!

Since Netlify isn't doing the build and deploy for me, it was not able to inject the environment variable set on the Netlify web app. Therefore, I had to add my environment variables to the `build` job:

```yml
name: Deploy to Netlify

on:
  push:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hallee/eslint-action@1.0.3
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
  deploy-to-production:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn
      - name: Build
        run: yarn build
        env:
          REACT_APP_ENV: ${{ secrets.REACT_APP_ENV }}  # <-- added this
      - name: Deploy
        uses: nwtgck/actions-netlify@v1.1
        with:
          deploy-message: ${{ github.event.head_commit.message }}
          enable-commit-comment: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
          production-branch: master
          production-deploy: true
          publish-dir: 'build'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
```
