### ISSUE TITLE
Action uploads to an additional URL as well, how to disable it?

### ISSUE THREAD

**Issue by Jarmos-san** [nwtgck/actions-netlify#504]
First off, thanks for your work, it's been an immense help!

I've been using this Action for quite a while & noticed search indexers crawling URLs which looks surprisingly like mine. It takes the form of `<ALPHANUMERIC-STRING>--jarmos.netlify.app`. Suffice to say it's hurting my indexing & SEO ratings due to duplicate entries in to the index.

After digging around a bit, I figured it's the Netlify which is deploying to more than one URL. I attached a screenshot highlighting the same. Refer to it below:

![image](https://user-images.githubusercontent.com/31373860/115018144-258aad00-9ed5-11eb-9817-e0c4ffc86d3e.png)

How do I enable to Action to only output the production URL & nothing else?

Here's the [workflow file](https://github.com/Jarmos-san/blog/blob/dev/.github/workflows/build.yml) I'm using to build the site before deploying to Netlify:

```yaml
name: Netlify Deploy

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.82.0"
      - name: Generate Static Content
        run: hugo --minify
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.1.13
        with:
          publish-dir: "./public"
          production-branch: dev
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deployed with GitHub Actions"
          netlify-config-path: ./netlify.toml
          github-deployment-environment: "Netlify Deploy"
          enable-pull-request-comment: false
          enable-commit-comment: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
```

Am I doing something wrong or is it intended behaviour? If it's the latter, is there any way I could disable it?
