### ISSUE TITLE
Deploy to additional branches

### ISSUE THREAD

**Issue by bzivyon** [nwtgck/actions-netlify#534]
I am trying to use the action and it works great on Deploy Preview and Production.
But not in Staging branch, the issue is that although the deployment URL seems to be correct (since I use `alias` option), the environment code is not updated.

This is what I set up in my project settings in Netlify:
![image](https://user-images.githubusercontent.com/58657522/117024687-e2b53b80-ad02-11eb-91e0-60b2e33045c1.png)

This is the code of the action:
```
- name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ env.NETLIFY_SITE_ID }}
        with:
          publish-dir: ${{ env.WORKING_DIRECTORY }}/dist
          production-branch: master
          github-token: ${{ secrets.READ_GITHUB_TOKEN }}
          github-deployment-environment: deploy preview
          enable-commit-comment: false
          deploy-message: ${{ env.SHORT_COMMIT_MESSAGE }}
          alias: ${{ env.GIT_BRANCH }}
```

I tried a lot of [options](https://github.com/marketplace/actions/netlify-actions#optional-inputs) but nothing helped and I would be very happy if you could help or advice. Thanks
