### ISSUE TITLE
Clarify purpose of `github-deployment-environment`

### ISSUE THREAD

**Issue by polarathene** [nwtgck/actions-netlify#538]
`github-deployment-environment` is only used for assignment to deploying to a different environment?

I didn't seem to be able to run the workflow and provide the secrets to ENV vars that the action uses unless I specify the environment (`netlify`) that I assigned the secrets to. However, that seems to cause an automated deploy status by myself (to which I can optionally provide a URL). I think this cancels the action that also attempts to deploy:

![Screenshot_20210506_212209](https://user-images.githubusercontent.com/5098581/117274853-93613d80-aeb1-11eb-92ee-dc65007ce952.png)

If I remove `github-deployment-environment`, I get a similar result, but the action defaults to `pull request`:

![Screenshot_20210506_213355](https://user-images.githubusercontent.com/5098581/117276569-22bb2080-aeb3-11eb-9bec-ef1c18a6a471.png)

While I like the added deploy links to the related workflow runs that this action seems to be missing, I'd prefer only the `github-actions[bot]` is running the deployment status update.

I'm not sure if this can be avoided, it seems to be caused by adding [`<job>.environment`](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idenvironment) (as below in config example) - but AFAIK the action doesn't seem to be able to access the secrets from ENV with `github-deployment-environment: netlify`, nor can I pass those in as I had been doing prior to assigning the secrets to a deployment environment (that only seems to work if I explicitly set the `environment` on the `job`).

---

Relevant workflow snippet:

```yml
jobs:
  preview:
    name: 'Deploy Preview'
    runs-on: ubuntu-20.04
    # non-default environment contains the NETLIFY_* secrets below
    # Note: This setting implicitly enables another deployment status?
    environment:
      name: netlify
      url: ${{ steps.preview.outputs.deploy-url }} # required to add the "View Deployment" button (github action bot doesn't have this issue for it's own deploy status)
    steps:
      - uses: actions/checkout@v2

      - name: 'Send preview build to Netlify'
        id: preview
        uses: nwtgck/actions-netlify@v1.2
        timeout-minutes: 1
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-deployment-environment: netlify # otherwise defaults to `pull request`
          enable-pull-request-comment: false
          enable-commit-comment: false
          enable-commit-status: false

      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: preview
          message: |
            [Documentation preview for this PR](${{ steps.preview.outputs.deploy-url }}) is ready! :tada:

            Built with commit ${{ github.event.pull_request.head.sha }}
```

This issue isn't too important to resolve. I'm just trying out the environment feature, and seeing if I could get it to work smoothly with this action (not sure if I can avoid the duplicate status issue).

Perhaps instead of "Environment name of GitHub Deployments" for the `github-deployment-environment` description, it could be "Environment name of GitHub Deployment target (default: `pull request`)" or something along those lines?
