### ISSUE TITLE
Netlify not commenting with Display Preview on PR

### ISSUE THREAD

**Issue by Shaquu** [nwtgck/actions-netlify#678]
Hey, I am trying to make Netlify to comment with link to preview on successufly GH action.

Link is generated but no comment is added.

Workflow here: https://github.com/NRCHKB/NRCHKB.github.io/actions/runs/1403407029/workflow
```
      - name: Netlify Actions
        uses: nwtgck/actions-netlify@v1.2.2
        with:
          publish-dir: './public'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN_NRCHKB_WIKI }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_NRCHKB_WIKI }}
```

Action here: https://github.com/NRCHKB/NRCHKB.github.io/runs/4057360768?check_suite_focus=true
```
Run nwtgck/actions-netlify@v1.2.2
  with:
    publish-dir: ./public
  env:
    NETLIFY_AUTH_TOKEN: ***
    NETLIFY_SITE_ID: ***
🚀 Deployed on https://617dd6c925c04b114eb6a1fb--naughty-raman-c58f41.netlify.app
```

PR here: https://github.com/NRCHKB/NRCHKB.github.io/pull/103
