### ISSUE TITLE
No such file or directory when deploying

### ISSUE THREAD

**Issue by simon-tarr** [nwtgck/actions-netlify#716]
I have a `dbt` project with documentation I'd like to publish to Netlify. 

By default, `dbt` documentation is kept in /target (e.g. ~/my_project/target). I have therefore configured my Actions YAML file as:

```
name: Build and Deploy to Netlify
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2.3
        with:
          publish-dir: './target'
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1

```
On pushing to master I get the error:

```
Run nwtgck/actions-netlify@v1.2.3
  with:
    publish-dir: ./target
    production-branch: master
    github-token: ***
  env:
    NETLIFY_AUTH_TOKEN: ***
    NETLIFY_SITE_ID: ***
Error: ENOENT: no such file or directory, lstat '/home/runner/work/my_project/my_project/target'
```
Can anyone point me in the right direction to resolve this?
