### ISSUE TITLE
Netlify preview build not using build script

### ISSUE THREAD

**Issue by Shaquu** [nwtgck/actions-netlify#720]
Currently standard preview with comment to PR works.
I have issues regarding using custom build command for preview.
If successful urls on preview should consist of DEPLOY_URL (not the one configured in config files, I tested locally the same command and it worked).

`gh action`
```yaml
      - name: Netlify Actions
        uses: nwtgck/actions-netlify@v1.2.3
        with:
          publish-dir: "./public"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-config-path: ./netlify.toml
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN_NRCHKB_WIKI }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_NRCHKB_WIKI }}
```

`netlify.toml`
```toml
[context.deploy-preview]
command = "hugo -b $DEPLOY_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.76"
```

Run
https://github.com/NRCHKB/NRCHKB.github.io/commit/622caa8c8b06bc02eb6b5f16f1ceb0773a263141
