### ISSUE TITLE
Production deployment not working

### ISSUE THREAD

**Issue by peschee** [nwtgck/actions-netlify#734]
I have the following config in my GH action workflow:

```yaml
- name: Deploy to Netlify
  uses: nwtgck/actions-netlify@v1.2.3
  with:
    publish-dir: './storybook-static'
    production-deploy: true
    github-token: ${{ secrets.GITHUB_TOKEN }}
    deploy-message: "Deploy from GitHub Actions"
    enable-commit-comment: false
  env:
    NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
    NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
  timeout-minutes: 1
```

and the action log outputs:

<img width="689" alt="image" src="https://user-images.githubusercontent.com/63866/156310506-6ccf67d7-cb39-40bf-a600-3dfe02341ddf.png">

the last two lines state:

>🎉 Published on https://inventage-web-components.netlify.app/ as production
>🚀 Deployed on https://621e43c1990d8e4944cef5e9--inventage-web-components.netlify.app

However, the version at the production URL (https://inventage-web-components.netlify.app/) is never updated. The preview URL (https://621e43c1990d8e4944cef5e9--inventage-web-components.netlify.app) works fine and contains the latest version.

Builds are turned off on Netlify.

Am I doing something wrong? I cannot get the production URL to serve the latest version deployed.
