### ISSUE TITLE
Use with page speed insights

### ISSUE THREAD

**Issue by kaihendry** [nwtgck/actions-netlify#84]
Could you please illustrate how you would use https://github.com/nwtgck/actions-netlify#outputs with https://github.com/marketplace/actions/page-speed-insights ?

Thank you!

**Comment by nwtgck** [comment]
@kaihendry Hi,

Here is the yaml.

```yaml
...
      - name: Running Page Speed Insights
        uses: jakepartusch/psi-action@v1
        with:
          url: ${{ steps.deploy-to-netlify.outputs.deploy-url }}
          threshold: 70
          strategy: mobile
```

Here is the actual changes: https://github.com/nwtgck/actions-netlify/pull/85/commits/85450f952f626b64861a3facdb5d19519fea07f8

## Result
<img width="868" alt="image" src="https://user-images.githubusercontent.com/10933561/78555772-acc82e00-7848-11ea-9f27-bdcb68f15007.png">

Actions: <https://github.com/nwtgck/actions-netlify/pull/85/checks?check_run_id=564141914>

**Comment by kaihendry** [comment]
Didn't work on https://github.com/kaihendry/dabase.com/pull/10 ... any ideas why?

Something obviously with the URL https://github.com/kaihendry/dabase.com/pull/10/checks?check_run_id=566227674

Maybe the name is wrong? https://github.com/kaihendry/dabase.com/blob/master/.github/workflows/netlify.yml

**Comment by kaihendry** [comment]
Would prefer to see Pagespeed output on the PR itself...

![image](https://user-images.githubusercontent.com/765871/78623132-91e1d200-78b9-11ea-85a4-79eae34ca111.png)

**Comment by nwtgck** [comment]
I'm not sure why the error caused. But it says " ##[error]Url is required to run Page Speed Insights."

<img width="492" alt="image" src="https://user-images.githubusercontent.com/10933561/78630014-95825280-78d3-11ea-9bf7-25f7173277b6.png">

**Comment by nwtgck** [comment]
Have you tried the following setting? Because the error might not cause by actions-netlify.
```
        with:
          url: "https://dabase.com/"
          threshold: 70
          strategy: mobile
```
